
group_dict = {
	'all_groups' : [], 'emtiyaz' : [],
'groh_dasteh' : [], 'games_type' : '',
	'cup_name' : [], 'group_groups' : [], 'all_teamss' : [],
	'groups_number' : [], 'groups_name' : [], 'number_of_teams' : [],
	'group_1_list' : [], 'groups_name' : [], 'copy_group_1_list' : [],
	'group_1_lottery' : [], 'game_team_grupe_1' : [], 'bazi_mizban_1' : [],
	'natijeh_bazi_mizban_1' : [], 'scopa_mizban_1' : [], 'bazi_mihman_1' : [],
	'natijeh_bazi_mihman_1' : [], 'scopa_mihman_1' : [],
	'group_2_list' : [], 'copy_group_2_list' : [], 'group_2_lottery' : [],
	'game_team_grupe_2' : [], 'bazi_mizban_2' : [], 'natijeh_bazi_mizban_2' : [],
	'scopa_mizban_2' : [], 'bazi_mihman_2' : [], 'natijeh_bazi_mihman_2' : [], 'scopa_mihman_2' : [],
	'group_3_list' : [], 'copy_group_3_list' : [], 'group_3_lottery' : [],
	'game_team_grupe_3' : [], 'bazi_mizban_3' : [], 'natijeh_bazi_mizban_3' : [],
	'scopa_mizban_3' : [], 'bazi_mihman_3' : [], 'natijeh_bazi_mihman_3' : [], 'scopa_mihman_3' : 	[],
	'group_4_list' : [], 'copy_group_4_list' : [], 'group_4_lottery' : [],
	'game_team_grupe_4' : [], 'bazi_mizban_4' : [], 'natijeh_bazi_mizban_4' : [],
	'scopa_mizban_4' : [], 'bazi_mihman_4' : [], 'natijeh_bazi_mihman_4' : [], 'scopa_mihman_4' : [],
	'group_5_list' : [], 'copy_group_5_list' : [], 'group_5_lottery' : [],
	'game_team_grupe_5' : [], 'bazi_mizban_5' : [], 'natijeh_bazi_mizban_5' : [],
	'scopa_mizban_5' : [], 'bazi_mihman_5' : [], 'natijeh_bazi_mihman_5' : [], 'scopa_mihman_5' : [],
	'group_6_list' : [], 'copy_group_6_list' : [], 'group_6_lottery' : [],
	'game_team_grupe_6' : [], 'bazi_mizban_6' : [], 'natijeh_bazi_mizban_6' : [],
	'scopa_mizban_6' : [], 'bazi_mihman_6' : [], 'natijeh_bazi_mihman_6' : [], 'scopa_mihman_6' : [],
	'group_7_list' : [], 'copy_group_7_list' : [], 'group_7_lottery' : [],
	'game_team_grupe_7' : [], 'bazi_mizban_7' : [], 'natijeh_bazi_mizban_7' : [],
	'scopa_mizban_7' : [], 'bazi_mihman_7' : [], 'natijeh_bazi_mihman_7' : [], 'scopa_mihman_7' : [],
	'group_8_list' :[], 'copy_group_8_list' :[], 'group_8_lottery' : [],
	'game_team_grupe_8' : [], 'bazi_mizban_8' : [], 'natijeh_bazi_mizban_8' : [],
	'scopa_mizban_8' : [], 'bazi_mihman_8' : [], 'natijeh_bazi_mihman_8' : [], 'scopa_mihman_8' : [],
'group_9_list' : [], 'copy_group_9_list' : [], 'group_9_lottery' : [],
	'game_team_grupe_9' : [], 'bazi_mizban_9' : [], 'natijeh_bazi_mizban_9' : [],
	'scopa_mizban_9' : [], 'bazi_mihman_9' : [], 'natijeh_bazi_mihman_9' : [], 'scopa_mihman_9' : [],	
	'group_10_list' : [], 'copy_group_10_list' : [], 'group_10_lottery' : [],
	'game_team_grupe_10' : [], 'bazi_mizban_10' : [], 'natijeh_bazi_mizban_10' : [],
	'scopa_mizban_10' : [], 'bazi_mihman_10' : [], 'natijeh_bazi_mihman_10' : [], 'scopa_mihman_10' : [],
	'group_11_list' : [], 'copy_group_11_list' : [], 'group_11_lottery' : [],
	'game_team_grupe_11' : [], 'bazi_mizban_11' : [], 'natijeh_bazi_mizban_11' : [],
	'scopa_mizban_11' : [], 'bazi_mihman_11' : [], 'natijeh_bazi_mihman_11' : [], 'scopa_mihman_11' : [],
	'group_12_list' : [], 'copy_group_12_list' : [], 'group_12_lottery' : [],
	'game_team_grupe_12' : [], 'bazi_mizban_12' : [], 'natijeh_bazi_mizban_12' : [],
	'scopa_mizban_12' : [], 'bazi_mihman_12' : [], 'natijeh_bazi_mihman_12' : [], 'scopa_mihman_12' : [],
		'group_13_list' : [], 'copy_group_13_list' : [], 'group_13_lottery' : [],
	'game_team_grupe_13' : [], 'bazi_mizban_13' : [], 'natijeh_bazi_mizban_13' : [],
	'scopa_mizban_13' : [], 'bazi_mihman_13' : [], 'natijeh_bazi_mihman_13' : [], 'scopa_mihman_13' : [],
		'group_14_list' : [], 'copy_group_14_list' : [], 'group_14_lottery' : [],
	'game_team_grupe_14' : [], 'bazi_mizban_14' : [], 'natijeh_bazi_mizban_14' : [],
	'scopa_mizban_14' : [], 'bazi_mihman_14' : [], 'natijeh_bazi_mihman_14' : [], 'scopa_mihman_14' : [],
		'group_15_list' : [], 'copy_group_15_list' : [], 'group_15_lottery' : [],
	'game_team_grupe_15' : [], 'bazi_mizban_15' : [], 'natijeh_bazi_mizban_15' : [],
	'scopa_mizban_15' : [], 'bazi_mihman_15' : [], 'natijeh_bazi_mihman_15' : [], 'scopa_mihman_15' : [],
		'group_16_list' : [], 'copy_group_16_list' : [], 'group_16_lottery' : [],
	'game_team_grupe_16' : [], 'bazi_mizban_16' : [], 'natijeh_bazi_mizban_16' : [],
	'scopa_mizban_16' : [], 'bazi_mihman_16' : [], 'natijeh_bazi_mihman_16' : [], 'scopa_mihman_16' : [],
	'ejazeh_1' : '', 'ejazeh_2' : '', 'ejazeh_3' : '',
	'ejazeh_4' : '', 'ejazeh_5' : '', 'ejazeh_6' : '',
	'ejazeh_7' : '', 'ejazeh_8' : '',
	'ejazeh_9' : '', 'ejazeh_10' : '', 'ejazeh_11' : '', 'ejazeh_12' : '',
	'ejazeh_13' : '', 'ejazeh_14' : '', 'ejazeh_15' : '', 'ejazeh_16' : ''




}


